#!/bin/sh

run_in_background() {
    local command="$1"
    local description="$2"

    printf "\033[1;32m[INFO]\033[0m Uruchamiam w tle: \033[1;34m%s\033[0m\n" "$description"
    (sh -c "$command" > /dev/null 2>&1 &)
}

printf "\n\033[1;33m───────────────────────────────────────────────────────────\033[0m\n"
printf "\033[1;33mKSB post-merge (1.0.1): Uruchamianie procesów w tle...\033[0m\n"
printf "\033[1;33m───────────────────────────────────────────────────────────\033[0m\n\n"

run_in_background "composer install && php artisan migrate && php artisan optimize" "composer install && php artisan migrate && php artisan optimize"

printf "\n\033[1;32m───────────────────────────────────────────────────────────\033[0m\n"
printf "\033[1;32mKSB post-merge (1.0.1): Wszystkie komendy uruchomione w tle.\033[0m\n"
printf "\033[1;32m───────────────────────────────────────────────────────────\033[0m\n\n"

#printf "\033[1;32m[INFO]\033[0m Weryfikuje integralność configu..."
#
#php artisan config:check

cp .git-sample/hooks/post-merge .git/hooks/post-merge

printf "\033[1;33m[INFO]\033[0m Skrypt został zaktualizowany z kopii w \033[1;34m.git-sample/hooks/post-merge\033[0m\n\n"

printf "\033[1;33m[INFO]\033[0m Skrypt uruchomiony w tle. Możesz nadal korzystać z terminala.\n"
